Additional crate documentation about usage fundamentals.
maciejhirsz/logos pull request #262
Opened 2022-08-18 23:17 UTC by Lokathor

This adds a small amount of extra documentation to the crate level docs about how to get started using the crate.

2022-08-19 08:50 UTC, domenicquirl commented on logos/src/lib.rs
> +//!   or write a callback expression inline (`eg: `|lex| lex.slice().chars().next().unwrap()`).
```suggestion
//!   or write a callback expression inline (eg: `|lex| lex.slice().chars().next().unwrap()`).
```
Apologies for the unplanned drive-by review.

2023-02-26 17:22 UTC, maciejhirsz commented on logos/src/lib.rs
> +//! use logos::{Logos, Lexer};
```suggestion
//! use logos::Logos;
```

2023-02-26 17:24 UTC, maciejhirsz requested changes
I get that these make it easier to understand what's going on, but it might make users think that's what they _have to do_, which would be misleading. Explaining the type in a comment would be better IMHO.

2023-02-26 17:24 UTC, maciejhirsz commented on logos/src/lib.rs
> +//!     let mut lex: Lexer<_> = Token::lexer("Create ridiculously fast Lexers.");
```suggestion
//!     let mut lex = Token::lexer("Create ridiculously fast Lexers.");
```

2023-02-26 17:24 UTC, maciejhirsz commented on logos/src/lib.rs
> +//! use logos::{Logos, Lexer};
```suggestion
//! use logos::Logos;
```

2023-05-22 01:40 UTC, closed without merging