use precise capturing on 1.82+
maciejhirsz/logos pull request #435
Opened 2024-11-12 16:47 UTC by indietyp

Fixes https://github.com/maciejhirsz/logos/issues/434 by conditionally adding `+ use<'s>` to the implementation of the callback, but _only_ if on 1.82+

Additionally it adds tests for the MSRV and 1.82 to the CI.

2024-11-12 19:39 UTC, jeertmans requested changes
Looks great, thanks for being so quick!

Please take a look a my comments.

2024-11-12 19:39 UTC, jeertmans commented on .github/workflows/rustlib.yml
You just probably turn off your formatter here and only apply changes ;-)

2024-11-12 19:39 UTC, jeertmans commented on logos-codegen/build.rs
I think this would be great to add some comments pointing back to your original issue, so we know where it comes from :-)

2024-11-12 19:40 UTC, indietyp commented on .github/workflows/rustlib.yml
I yea sorry my code editor kinda just did it here, will revert the change.

2024-11-13 08:20 UTC, jeertmans commented
As indicated by the CI, I think the new build dependency requires us to bump the MSRV to 1.74

2024-11-13 09:01 UTC, indietyp commented
I don't think this is actually caused by the new build-dependency (it also has `semver` as a dependency) I think the issue exists because the toolchain was never before tested (see the `{{matrix.rust}}` addition). I think this might be a problem with rstest.

2024-11-13 09:04 UTC, indietyp commented on logos-codegen/build.rs
see [fc71df4](https://github.com/maciejhirsz/logos/pull/435/commits/fc71df4372c02bc06c6ad0469fa3a510613a8dba)

2024-11-13 09:04 UTC, indietyp commented on .github/workflows/rustlib.yml
see [89ee9dc](https://github.com/maciejhirsz/logos/pull/435/commits/89ee9dc2f814a4d693a935d740f9a69fcc4114f2)

2024-11-13 09:07 UTC, indietyp commented
actually correction, looking at the output of `cargo tree --workspace` the issue is `logos-cli`:

https://github.com/maciejhirsz/logos/blob/491842d0adb9689e9fa707e6fb89b97f1a59fe28/logos-cli/Cargo.toml#L11

2024-11-13 10:45 UTC, jeertmans commented
> I don't think this is actually caused by the new build-dependency (it only has `semver` as a dependency) I think the issue exists because the toolchain was never before tested (see the `{{matrix.rust}}` addition). I think this might be a problem with rstest.

I see, but I don't get why the `msrv_check` workflow didn't catch this before...



> actually correction, looking at the output of `cargo tree --workspace` the issue is `logos-cli`:
> 
> https://github.com/maciejhirsz/logos/blob/491842d0adb9689e9fa707e6fb89b97f1a59fe28/logos-cli/Cargo.toml#L11

You are right, I was too quick on my conclusions :-)

2024-11-13 10:46 UTC, jeertmans commented on logos-codegen/build.rs
Great thanks!

2024-11-13 10:46 UTC, jeertmans commented on .github/workflows/rustlib.yml
No issue, thanks!

2024-11-13 10:49 UTC, indietyp commented
We could either raise the MSRV to 1.74, raise the CI to only test 1.74 or downgrade predicates to something that supports 1.70

2024-11-13 10:59 UTC, jeertmans commented
> We could either raise the MSRV to 1.74, raise the CI to only test 1.74 or downgrade predicates to something that supports 1.70

I think the issue is actually the CI doesn't use `--locked`, so this is probably why the issue wasn't discovered before.

For the sake of simplicity, we can just bump to 1.74 here.

2024-11-13 15:11 UTC, jeertmans commented on Cargo.toml
> +msrv = "1.70.0" # Needed to duplicate, because cargo-msrv does not support workspace
I think you need to also update this field

2024-11-16 11:51 UTC, jeertmans commented
Looks all good @indietyp, thanks!

2024-11-16 11:51 UTC, jeertmans approved these changes

2024-11-16 11:52 UTC, merged